# application.yml
server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: ijeong0416
    password: 340834
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          default_batch_fetch_size: 100
          format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG # SQL 쿼리 출력
    org.hibernate.type: TRACE # 파라미터와 타입 정보 출력
